apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
spec:
  generators:
  - git:
      repoURL: https://github.com/satyam-01-byte/argocd-test-gh.git
      revision: HEAD
      files:
      - path: example/*/*.yaml
  template:
    metadata:
      name: '{{path[1]}}'
    spec:
      project: default
      source:
        directory:
          recurse: true
        repoURL: https://github.com/satyam-01-byte/argocd-test-gh.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
